Update and rename reset-rmf-web-api-server.bash to reset-rmf-web

diff --git a/reset-rmf-web b/reset-rmf-web
--- a/reset-rmf-web
+++ b/reset-rmf-web
@@ -5,8 +5,30 @@ PARAMS=""
 while (( "$#" )); do
   case "$1" in
     --help)
-      echo "Usage: reset-rmf-web-api-server webMachineName [login@hostname of machine running rmf-web] --webIdentityFile [path to ssh key of webMachineName"
+      echo "Usage: reset-rmf-web-api-server webMachineName [login@hostname of machine running rmf-web] --webIdentityFile [path to ssh key of webMachineName] --simTime [true|false]  --levelName [ name of level to visualize ]"
       exit 0
+      ;;
+    -s|--simTime)
+      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
+	USE_SIM_TIME=$2
+        shift 2
+      else
+        echo "Error: Argument for $1 (useSimTime) is missing" >&2
+        exit 1
+      fi
+      ;;
+    -l|--levelName)
+      if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
+        LEVEL_NAME=$2
+        shift 2
+      else
+        echo "Error: Argument for $1 (levelName) is missing" >&2
+        exit 1
+      fi
+      ;;
+    -*|--*=) # unsupported flags
+      echo "Error: Unsupported flag $1" >&2
+      exit 1
       ;;
     -wi|--webIdentityFile)
       if [ -n "$2" ] && [ ${2:0:1} != "-" ]; then
@@ -41,9 +63,13 @@ eval set -- "$PARAMS"
 
 WEB_MACHINE_NAME="${WEB_MACHINE_NAME:-root@rmf-web.local}"
 WEB_IDENTITY_FILE="${WEB_IDENTITY_FILE:-/home/ubuntu/.ssh/id_rmf}"
+USE_SIM_TIME="${USE_SIM_TIME:-false}"
+LEVEL_NAME="${LEVEL_NAME:-L1}"
 
 echo "WEB_MACHINE_NAME: $WEB_MACHINE_NAME"
 echo "WEB_IDENTITY_FILE: $WEB_IDENTITY_FILE"
+echo "USE SIM TIME: $USE_SIM_TIME"
+echo "LEVEL_NAME: $LEVEL_NAME"
 
 read -p "Continue? [Yy] " -n 1 -r
 echo    # (optional) move to a new line
@@ -51,6 +77,9 @@ if [[ $REPLY =~ ^[Yy]$ ]]
 then
 	ssh -i $WEB_IDENTITY_FILE $WEB_MACHINE_NAME "kubectl delete -f /home/web/rmf-web/example-deployment/k8s/rmf-server.yaml; kubectl apply -f /home/web/rmf-web/example-deployment/k8s/rmf-server.yaml"
 	ssh -i $WEB_IDENTITY_FILE $WEB_MACHINE_NAME "wg-quick down wg0; wg-quick up wg0;"
+	ssh -i $WEB_IDENTITY_FILE $WEB_MACHINE_NAME "pkill -f schedule_visualizer"
+	ssh -i $WEB_IDENTITY_FILE $WEB_MACHINE_NAME "pkill -f visualization"
+	ssh -X -i $WEB_IDENTITY_FILE $WEB_MACHINE_NAME ". .profile; nohup ros2 launch rmf_visualization visualization.launch.xml use_sim_time:=$USE_SIM_TIME viz_config_file:=/opt/rmf/src/demonstrations/rmf_demos/rmf_demos/launch/include/office/office.rviz headless:=1 map_name:=$LEVEL_NAME | tee /root/tailon_logs/current_launch.log" 
 else
   echo "Abort."
 fi
